### PR TITLE
Dynamic NFT

### PR DESCRIPTION
**Pull request by tequdev**
including merge from XRPLF/rippled:develop branch

- URI field is an optional field; if not specified, the URI field in NFToken is deleted

### CODE REVIEW

**Comment by tequdev** [comment]
Need to consider whether to allow a change to the same URI as before the change (empty transaction execution)

**Comment by mvadari** [comment]
I'd recommend doing the merge commit and actual changes separately, so it's easier to understand what the changes are.

**Comment by tequdev** [comment]
> I'd recommend doing the merge commit and actual changes separately, so it's easier to understand what the changes are.

Here you can see the differences from the develop branch

https://github.com/tequdev/rippled/pull/5

**Comment by tequdev** [comment]
> Need to consider whether to allow a change to the same URI as before the change (empty transaction execution)

If implemented for the number of times remaining that can be modified, it could be something like sending an NFTokenModify transaction without modifying the URI to decrease only the number of times remaining.

**Pull request merged**
